# Generated by Django 5.1.2 on 2024-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
