# Generated by Django 5.1.2 on 2024-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_events_created_at_alter_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='Annonymous Email', max_length=200, null=True)),
                ('name', models.CharField(default='Annonymous', max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('opinion', models.TextField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
